### ISSUE TITLE
Preview y-offset

### ISSUE THREAD

**Issue by bastaware** [LouisBrunner/dnd-multi-backend#28] opened 2019-03-16 01:09 UTC
My first try didn't go too well. Hopefully it's something simple I've missed.

When I start dragging in touch mode (Chrome). The preview is at the top of the parent container (and dropTarget).

It works fine with react-dnd-html5-backend

![offy](https://user-images.githubusercontent.com/1000036/54468750-47faeb00-4790-11e9-9148-e80cd87c20e2.gif)

**Comment by LouisBrunner** [comment] 2019-09-22 15:37
This is a duplicate of #5, I am aware that this happens but I currently don't have a fix for it, sorry!

**Closed by LouisBrunner** 2019-09-22 15:37 UTC
