### ISSUE TITLE
Switch HTML5Backend <->TouchBackend not work.

### ISSUE THREAD

**Issue by Strori** [LouisBrunner/dnd-multi-backend#9] opened 2017-07-28 12:03 UTC
Hello.

Switch HTML5Backend -> TouchBackend works great, but after that doesn't want to switch back to HTML5Backend. 
Use : 
const HTML5_TO_TOUCH_TO_HTML5 = {
  backends: [
    {
      backend: HTML5Backend,
      transition: HTML5DragTransition,
    },
    {
      backend: TouchBackend({ enableMouseEvents: true }),
      transition: TouchTransition,
    }
  ]
};

**Comment by LouisBrunner** [comment] 2017-07-29 21:34
Hey @Strori,

I noticed this before, it seems to be a browser limitation.

If you monitor the events you can see that once the browser received a `Touch` event, it never generates `Drag` event anymore.

Here is an example on Chrome:

<img width="495" alt="browserevents" src="https://user-images.githubusercontent.com/7120871/28748303-2440a4e2-74ac-11e7-9eeb-72494962d739.png">

After `touchstart` was sent, `dragstart` is never sent again. However you can just create your own transition listening for `mousedown`, here is a simple example:

```
import { createTransition } from 'react-dnd-multi-backend';

export const MouseTransition = createTransition('mousedown', (event) => {
  return true;
});
```

Then, just replace `HTML5DragTransition` by `MouseTransition`.

**Comment by Strori** [comment] 2017-07-31 06:22
Thank you. I will try your recommendation.

**Comment by Strori** [comment] 2017-08-01 13:18
Hello, after your recommendation have new error "Uncaught RangeError: Maximum call stack size exceeded." on last line this function  
 this.backendSwitcher = function (event) {
    var oldBackend = _this.current;

    var i = 0;
    var _iteratorNormalCompletion3 = true;
    var _didIteratorError3 = false;
    var _iteratorError3 = undefined;

    try {
      for (var _iterator3 = _this.backends[Symbol.iterator](), _step3; !(_iteratorNormalCompletion3 = (_step3 = _iterator3.next()).done); _iteratorNormalCompletion3 = true) {
        var backend = _step3.value;

        if (i !== _this.current && backend.transition && backend.transition.check(event)) {
          _this.current = i;
          break;
        }
        i += 1;
      }
    } catch (err) {
      _didIteratorError3 = true;
      _iteratorError3 = err;
    } finally {
      try {
        if (!_iteratorNormalCompletion3 && _iterator3.return) {
          _iterator3.return();
        }
      } finally {
        if (_didIteratorError3) {
          throw _iteratorError3;
        }
      }
    }

    if (_this.current !== oldBackend) {
      _this.backends[oldBackend].instance.teardown();
      var _iteratorNormalCompletion4 = true;
      var _didIteratorError4 = false;
      var _iteratorError4 = undefined;

      try {
        for (var _iterator4 = Object.keys(_this.nodes)[Symbol.iterator](), _step4; !(_iteratorNormalCompletion4 = (_step4 = _iterator4.next()).done); _iteratorNormalCompletion4 = true) {
          var id = _step4.value;

          var node = _this.nodes[id];
          node.handler();
          node.handler = _this.callBackend(node.func, node.args);
        }
      } catch (err) {
        _didIteratorError4 = true;
        _iteratorError4 = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion4 && _iterator4.return) {
            _iterator4.return();
          }
        } finally {
          if (_didIteratorError4) {
            throw _iteratorError4;
          }
        }
      }

      _this.backends[_this.current].instance.setup();

      var newEvent = new event.constructor(event.type, event);
      event.target.dispatchEvent(newEvent);
    }
  };

**Comment by Strori** [comment] 2017-08-01 15:05
Sorry, my mist. All works.

**Comment by cormacrelf** [comment] 2018-01-03 04:12
The following works so well it could be the default. It would support browsers that do touch AND mouse (like Chrome/FF on Windows 10 with touch). And it kills the requirement for the buggy `{enableMouseEvents: true}` on the touch backend, which just causes issues left right and center [apparently](https://github.com/yahoo/react-dnd-touch-backend/issues/88). I haven't tested this everywhere, but it works because when you listen to 'mousedown' you also get 'touchstart'.

```
const MouseTransition = createTransition('mousedown', (e) => {
    return e.type
        && e.type.indexOf('touch') === -1
        && e.type.indexOf('mouse') !== -1;
});

const HTML5ToTouch = {
    backends: [
        {
            backend: HTML5Backend,
        },
        {
            backend: TouchBackend({ enableMouseEvents: false }),
            preview: true,
            transition: TouchTransition,
        },
        {
            backend: HTML5Backend,
            transition: MouseTransition,
        },
    ],
};
```

**Comment by cormacrelf** [comment] 2018-01-03 12:34
Oh, incidentally, I think the reason HTM5DragTransition doesn’t do anything is that the h5 backend is responsible for adding the “draggable” attribute to elements, and once you swap it out, those attributes are removed, and there aren’t any draggable events to fire dragstart events on. So the transition will never cause multi backend to switch. At least I think so.

**Comment by LouisBrunner** [comment] 2018-01-07 11:49
@cormacrelf,

You are right, this makes way more sense!
I just pushed v3.1.0 (available on the `next` tag on npm) which includes your suggestion (transition + HTML5toTouch).

**Comment by renak** [comment] 2018-01-25 22:44
Thanks for your 3.1.0 change. It works pretty well! Do you know when it will be officially released? The import statement in react-dnd-multi-backend package will need to be updated as well.

I was having the issue @cormacrelf described, where the html5 backend was setting the "draggable" attribute to false right before the multibackend switcher swapped backends. Then once switched to touch-backend, dragging interactions would not happen in some versions of android Chrome because that attribute was false. I was able to fix this issue by putting the touch-backend first in my backends array. This way, on mobile devices the html5 backend never loads and thus never sets "draggable" to false.

```
const HTML5toTouch = {
	backends: [
		{
			backend: TouchBackend({ enableMouseEvents: true, delayTouchStart: 500 }),
			preview: true,
			transition: TouchTransition,
		},
		{
			backend: HTML5Backend,
			transition: MouseTransition,
		},
	],
};
```

**Comment by LouisBrunner** [comment] 2018-01-27 09:35
Hi @renak,
I was waiting for some more feedback, so I guess I will release it now.

So you are saying that even with @cormacrelf improvement, you are still running into issues?

**Comment by renak** [comment] 2018-01-29 18:25
The change for v3.1.0 covers the issue originally posted in this thread - adding a transition to switch from touch backend to html5 backend. The fix for this seems to work great.

@cormacrelf mentioned a second issue, separate from the first issue, which I was experiencing. I was able to get around that issue simply by listing the touch-backend first and the html5 backend second in the backends array.

**Comment by davidschwegler** [comment] 2018-01-30 19:42
-  After this change, why does @cormacrelf not need the enableMouseEvents while @renak still does? 
- @renak which Android browsers were you experiencing the issue where swapping the TouchTransition first fixed it?

**Comment by cormacrelf** [comment] 2018-01-30 22:25
@davidschwegler I can’t be the only one thinking that `enableMouseEvents` is the real problem for @renak. Androids and iPhones do not care about `draggable` attributes.

**Comment by renak** [comment] 2018-01-30 23:22
I never really had any issues testing on the iOS devices. I'm seeing different behavior happening between 2 different Android phones I'm testing on (both Android 7):

- Nexus 6 with Chrome 63
- Samsung Galaxy S6 with Chrome 55

With **enableMouseEvents true** and **Html5 backend first**, draggable attribute was false. The Samsung was ignoring the draggable attribute and allowed the user to drag. The Nexus however would not performing the dragging interaction.

Then I kept **enableMouseEvents true**, but changed the array to have **Touch backend first**, with draggable being always true. Both phones functioned correctly with this setting.

Now, I've tried setting **enableMouseEvents false** and **Html5 backend first**, the Nexus functions correctly but the Samsung doesn't perform dragging.

I suspect that the draggable attribute does matter on some devices. 

On a side note, @LouisBrunner could we have the MouseTransition imported into the react-dnd-multi-backend package?

**Comment by LouisBrunner** [comment] 2018-02-04 12:28
Thanks for the detailed summary!

As we don't know what is causing these issues yet, I would recommend that you maintain your own `HTML5toTouch` for the time being. Once the problem is sorted, we'll adapt it to match the widest audience possible.

I completely missed `MouseTransition`, I'll include it at once.

**Comment by renak** [comment] 2018-02-05 23:34
I can `npm install` v3.1.1 of `react-dnd-multi-backend`, but it does not have your code changes for some reason.

**Comment by LouisBrunner** [comment] 2018-02-10 13:22
You're right, I must have an issue in my build/publish process. I republished `v.3.1.2`.

**Comment by Soundvessel** [comment] 2019-02-18 23:14
This might be related but I was having issues using the `Preview` component with `HTML5Backend`. Even though I had preview set to true in my custom pipeline I found that the "enabled" state was stuck to false unless I triggered a condition to make it switch pipelines.

Here was my original pipeline.

```
const backendsOld = {
  backends: [
    {
      backend: HTML5Backend,
      preview: true,
      transition: MouseTransition
    },
    {
      backend: TouchBackend({ enableMouseEvents: false }),
      preview: true,
      transition: TouchTransition
    }
  ]
};
```

Funny thing with the above pipeline I could enable to the Preview with mouse by loading Chrome inspector, toggling the device toolbar, dragging (with device toolbar on mouse events are triggered as touch) and turning off the device toolbar. It was only then that it appeared my `preview: true" setting o the `HTML5Backend` was loaded. Reloading the page and you are back to Preview not being enabled.

Switching to this custom pipeline (thanks @cormacrelf ) makes the Preview work no matter if you are on a desktop with mouse or touch device:

```
const backendsNew = {
  backends: [
    {
      backend: HTML5Backend
    },
    {
      backend: TouchBackend({ enableMouseEvents: false }),
      preview: true,
      transition: TouchTransition
    },
    {
      backend: HTML5Backend,
      preview: true,
      transition: MouseTransition
    }
  ]
};
```

I created a quick little codesandbox (https://codesandbox.io/s/13ll225xq3) where you can switch the two pipelines at line 50 and use the inspector as I mentioned above to see how options on `HTML5Backend` were not respected until another transition was triggered.

My guess is that the first item of the pipeline gets its options (preview and transition) ignored until you trigger the transition of another backend in the pipeline?

**Closed** 2020-03-01 23:19 UTC
Labels: bug
