### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by gnuletik** [LouisBrunner/dnd-multi-backend#23] opened 2018-06-06 17:38 UTC
The preview isn't displayed with react-dnd `^3.0.0` and react-dnd-multi-backend `^3.1.2` using the example provide in the repo.

Test repository: https://github.com/gnuletik/react-dnd-multi-backend-demo
Hosted demo: https://pensive-mcclintock-1ca257.netlify.com/

If you try to move an element with touch events, you realize that nothing is shown.
Did I miss something ?

**Comment by iPaul95** [comment] 2018-06-08 10:27
It doesn't work for touch events even on the rest repository, and when i tried to build my own preview, if i drag outside of target area the item goes back to it's place and becomes undraggable

**Comment by gnuletik** [comment] 2018-06-08 15:02
It seems to be working on my side.

Firefox "normal" mode
![peek 08-06-2018 17-00](https://user-images.githubusercontent.com/9059840/41165265-78a70584-6b3d-11e8-8ad7-a9798dffd19d.gif)

Firefox touch emulation mode
![peek 08-06-2018 17-02](https://user-images.githubusercontent.com/9059840/41165264-787b71f8-6b3d-11e8-8911-1147109fdf1a.gif)

As you can see, only the preview doesn't work with the touch backend

**Comment by LouisBrunner** [comment] 2018-06-17 21:02
Hi @gnuletik,

I believe this is a duplicate with #22 (the code that check if the preview should be shown fail and therefore the preview is never shown). Try the new version (`next` tag on npm) and re-open this issue if it's still happening, thanks!

**Comment by dawnmist** [comment] 2018-07-09 04:47
Lack of preview is still occurring for me with 3.1.4. There is no Preview drawn on iOS Safari, Chrome "responsive" mode, and Firefox in touch emulation mode.

**Comment by LouisBrunner** [comment] 2018-07-09 21:10
Thanks @dawnmist for the feedback, I can reproduce it on Firefox macOS. However on Chrome macOS  (67.0.3396.99), it works as expected, what is the platform you are testing on?

**Comment by LouisBrunner** [comment] 2018-07-09 21:21
Note that for me it does work in Firefox touch emulation mode, but doesn't in just "responsive mode".

**Comment by dawnmist** [comment] 2018-07-09 23:29
I was working on Centos 7 (linux).

I ended up moving to using the DragLayer instructions from react-dnd directly yesterday (as I needed to get things working for a demo this week), and noticed that the react-dnd instructions have the preview drawn inside a full-screen div. That div seems to be missing from the your Preview component, which might explain why the Preview isn't being mounted/shown.

**Comment by LouisBrunner** [comment] 2018-07-10 18:08
So I finally managed to reproduce the issue, I think my local repository has some problems with `package-lock.json`.

I think you have the names right, it is just that Firefox makes the difference between  "responsive mode" and "touch emulation".

I'll take a look tonight and try to find a fix.

**Comment by LouisBrunner** [comment] 2018-07-10 22:21
I think that should now be fixed on `next`.

The problem came from that the fact that `react-dnd` now uses a unique `React.createContext` to pass their `dragDropManager`. This means that projects need to use `peerDependencies` for `react-dnd` in order to share the exact same dependency and have corresponding `Producer`/`Consumer`.

**Closed by LouisBrunner** 2018-07-10 22:21 UTC
Labels: duplicate

**Comment by theTechie** [comment] 2018-07-11 07:57
@LouisBrunner - having React 16 as a peerDepedency makes it very strict and makes this library in-compatible with older versions of react. Is that right ?

I am using `react@15.6.2` and `react-dnd-multi-backend@3.1.2` and since `dnd-preview` used an older version of `react` which in-turn was still accessing `propTypes` from `react` (but not from `prop-types` library), i am getting deprecation warnings about access propTypes from react.

PS: i am in the process of upgrading to React16 and having trouble fixing these warnings as we are unable to upgrade to a specific version which is backwards compatible with React i.e. `react@15.6.2`

**Comment by LouisBrunner** [comment] 2018-07-11 09:04
@theTechie I can try to make it more generic, as it was before. I wanted to make it work with the latest `react-dnd`, so that's why I forced version.

**Comment by theTechie** [comment] 2018-07-11 09:35
That would be awesome @LouisBrunner ! 👍 

I am currently stuck with whatever version i have, unable to upgrade / downgrade to make it work. 

I am moving away from using this package for now. Please shoutout when you have a new release which makes it backward compatible.

Thanks !

**Comment by LouisBrunner** [comment] 2018-07-11 19:53
Note if you use `3.1.0` (`latest` tag) with `react-dnd` < `5.0`, you should be fine.

**Comment by LouisBrunner** [comment] 2018-07-11 20:05
The `next` tag (version `3.1.8`) now uses a wildcard for `react` related dependencies, as before.
